version: 2.1

jobs:
  compile:
    docker:
      - image: ubuntu:rolling
    steps:
      - run:
          name: "Running build setup script..."
          command: |
            apt update && apt upgrade -y
            apt install git wget -y
            git clone https://github.com/escawet-esc/android_build_environment .sc
            bash .sc/setup.sh

      - run:
          name: "Starting compile..."
          command: |
            git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            cd ${CIRCLE_PROJECT_REPONAME}
            bash build.sh

workflows:
  compiling:
    jobs:
      - compile
